# Profile section
profile:
  first_name: Miguel
  last_name: Camacho
  picture: static/img/profile.jpg
  contact: 
    address_one: Dolores Hidalgo, Guanajuato
    address_two: San Felipe, Guanajuato
    phone: (428) 68 70140
  email: miguel.cam.mx@gmail.com
  description: Im a programmer with java, python.
        
# Social section
social:
  website: 
  github: https://github.com/iammiguelmx/
  twitter: https://twitter.com/elmiguelmx/
  linkedin: https://www.linkedin.com/in/miguelcamacho/
  facebook: https://www.facebook.com/iammiguelmx/
  instagram: https://www.instagram.com/iammiguelmx/
  youtube: https://www.youtube.com/channel/UCFLCGFesBniye9vNwYe9HCg/

# Experience section
experience:
  item0:
    position: Programmer, Dev Ops Beginner
    company: SOMA Tecnologia y Medios de Pago
    from: March 2019
    to: Present
    description: >
     SOMA Tecnologia y Medios de Pago It is a company formed by a group of professionals in the 
     technological and financial sector (Non-Banking Financial Intermediaries), specialized in micro 
     finance, who decided to create a company to provide solutions to the financial sector (Non-Banking
     Financial Intermediaries) through a robust technological platform that includes the best business 
     practices for the sector.
    link: http://www.somatecnologia.com.mx/
  item1:
    position: Programmer
    company: MTI Consultoria
    from: August 2018
    to: December 2018
    description: > 
      Technological consulting specialized in administration and software development. 
      REGER-GRP tool that facilitates the accounting harmonization of government.
    link: http://www.mticonsultoria.com/

# Education section
education:
  item1:
    institution: Universidad Tecnologica del Norte de Guanajuato
    program: Bachelor's Degree Computer Enginner
    description: Licenciatura enfoca a la adminisraciòn de proyectos de TI
    from: August 2018
    to: August 2020
  item2:
    institution: Universidad Tecnologica del Norte de Guanajuato
    program: Bachelor's Degree Computer Enginner
    description: 
    from: August 2016
    to: July 2018
  

# Community section:
community:
  item1:
    institution: Casa de la cultura
    program: Symphonic Orchestra
    description: First voice with alto saxophone in the house of the culture of San Felipe, attended events in Leon Guanajuato, Anniversary of San Felipe
    from: September 2010
    to: December 2016
    link: http://sanfelipegto.gob.mx/direcciones/casadelacultura.html
  item2:
    institution: GitHub Student
    program: GitHub Student Program
    description: I have participated in different hackathons, programming events and workshops
    from: July 2018
    to: Present
    link: https://github.com/iammiguelmx

# Skills section
tools:
  # Consider that the following are fa icons:
  - java
  - python
  - github
  - slack
  - trello
  - markdown
  - html5
  - bootstrap
  - google

extra_skills:
  - Chatbots with Dialog Flow
  - APIs and web development
  - Consume API`s Java, Python, Rails
  - Firebase
  - Swift 
  - PWA Apps

# Certifications and awards section
awards:
  - Participe in HackDH 2019
  - Participe in LinceHach 2019
  - Participe in NASA Space Apps Guanajuato 2019
  - Aprende PHP desde cero PHP - emitted Udemy
  - Iniciando con Containers en Docker
  - Mastering Java for Beginners & Experts
  - The Guide of Scrum  - emitted Udemy
  - Aprende SQL desde cero - emitted Udemy
  
